-- Basic
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')

-- Plugins
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.cmp')
require('plugins.lsp')
require('plugins.mason')
require('plugins.autopairs')
require('plugins.autotag')
require('plugins.buffline')
require('plugins.comments')
require('plugins.dashboard')
require('plugins.telescope')
require('plugins.lualine')
require("plugins.whichkey")
require("plugins.gitsigns")
require("plugins.outline")
require("plugins.toggleterm")
